services:
  - type: web
    name: fujian-food-ai
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npm run build:server
    startCommand: node server-dist/index.js
    autoDeploy: true
    envVars:
      - key: CODEBUDDY_API_KEY
        value: ck_fsce77fc1g5c.tSttHT5Mdnuvz-6uwXBZSrylCIMmvCdbqjw1v7T7iT0
      - key: NODE_VERSION
        value: 22.22.2
